"""init

Revision ID: 693fc81383de
Revises: 99d9364b68df
Create Date: 2026-04-08 00:27:10.499287

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '693fc81383de'
down_revision: str | Sequence[str] | None = '99d9364b68df'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
